### ISSUE TITLE
Bug - Validation Page is not reacheable when the last page of questionnaire is inside a Loop

### ISSUE THREAD

**Issue by laurentC35** [InseeFr/Stromae#149]
- To reproduce this bug, I will give you a questionnaire soon
- I think it's because the props `isLastPage` (returned by lunatic) is equal to false and the `goNext` has no effect in Lunatic, see the code [here](https://github.com/InseeFr/Stromae/blob/v2-develop/src/components/orchestrator/collector/index.js#L165).
- Test with Stromae-v2 (https://stromae-v2.dev.insee.io) with versions : Stromae : 2.1.49 | Lunatic : 0.3.5-experimental

**Comment by laurentC35** [comment]
Maybe it's a Lunatic issue, but this bug can be resolved easily in Stromae

**Comment by AnneHuSKa** [comment]
Stromae : 2.1.69 | Lunatic : 0.3.9-experimental : same problem.
If you add <EndQuestion>, the validation page is reachable.
==> Lunatic issue
