### ISSUE TITLE
Modification of welcome.js

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Stromae#195]
1/ Ajouter une variable Enq_TestNonLabellise (oui/non) qui filtre le texte à afficher :

- si oui => 
Cette enquête non obligatoire relève de l'exercice des missions de service public dont est investi l’Insee (articles 4, 5 et 5 bis du règlement 223/2009 relatif aux statistiques européennes, article 1 de la [loi n° 51-711 du 7 juin 1951](" || Loi_statistique ||") sur l'obligation, la coordination et le secret en matière de statistiques, décret du 14 juin 1946 organisant l’Insee).
- si non => affichage des 2 premiers paragraphes comme aujourd'hui :
Vu l'avis favorable du Conseil national de l'information statistique...
Visa n°" || Enq_NumeroVisa || " du Ministre ...

2/ Remplacer la toute dernière phrase (actuellement : Les droits des personnes,  rappelés dans la lettre-avis, peuvent être exercés auprès de " || Enq_RespTraitement || ".)  par :  Ils garantissent aux personnes concernées un droit d'accès, de limitation ou de rectification pour les données les concernant. Ce droit peut être exercé auprès de" || Enq_RespTraitement ||".

**Comment by AnneHuSKa** [comment]
Stromae 2.2.11

**Comment by romaintailhurat** [comment]
Released with https://github.com/InseeFr/Bowie/releases/tag/1.0.0
