### ISSUE TITLE
Bug stateData

### ISSUE THREAD

**Issue by MickaelMenet** [InseeFr/Stromae#199]
At the end of the questionnaire a red screen appears. the stateData appears as undefined.
![image](https://user-images.githubusercontent.com/71713999/206680616-65d2b37c-a55e-4ee7-a793-2a53c14601e6.png)

**Comment by MickaelMenet** [comment]
En validation : https://github.com/InseeFr/Stromae/pull/201

**Comment by AnneHuSKa** [comment]
ok (Stromae 2.2.11

**Comment by romaintailhurat** [comment]
Released with https://github.com/InseeFr/Bowie/releases/tag/1.0.0
