### ISSUE TITLE
Reconnexion - retour systématique à la première séquence du questionnaire, à tort

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Stromae#203]
Lors de la déco/reco, quelque soit le choix fait ("revenir à la première page du questionnaire" ou "revenir à la dernière page accédée") on tombe sur la première séquence, ce qui est assez lourd pour le parcours enqueté.

https://github.com/InseeFr/Lunatic/issues/301 (a goPage(page) function in order to directly jump into a given page)
https://github.com/InseeFr/Lunatic/issues/302

**Comment by romaintailhurat** [comment]
Test non concluant avec ce qui est déployé ici : https://gotopage.demo.insee.io/visualize

Je teste avec le questionnaire SIMPSONS embarqué mais en fournissant [ce fichier JSON](https://minio.lab.sspcloud.fr/romaintailhurat/public/bowie/data_simpsons.json) de données.

**Comment by romaintailhurat** [comment]
Comportement correct avec nouvelle version (test avec le questionnaire famille embarqué)

**Comment by laurentC35** [comment]
Check deployed version

**Comment by laurentC35** [comment]
@@romaintailhura can you ping the version ?

**Comment by QRuhier** [comment]
Voir stratégie de déploiement entre StromaeV2 ou passage à StromaeV3

**Comment by romaintailhurat** [comment]
This issue will be handled for Stromae V3 only.
