### ISSUE TITLE
First page of the questionnaire with "business" and/or "SSP" context, in addition to the context "household" 

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Stromae#208]

**Comment by AnneHuSKa** [comment]
J'ai eu une proposition pour la partie Business, inspirée de la page ménages et avec ajout d'une variable. Comment tester svp une nouvelle page welcome.js ?

**Comment by romaintailhurat** [comment]
Un nouvel environnement sur un cluster kube 😄 (je comprends qu'un développement n'est pas nécessaire, mais ça n'est peut-être pas le cas).

**Comment by AnneHuSKa** [comment]
Stromae 2.4.1
