### ISSUE TITLE
Sauvegarde - peut-on revenir à la sauvegarde par page et non par séquence ?

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Stromae#214]
StromaeV1 : sauvegarde de chaque page
StromaeV2 : sauvegarde  à chaque séquence
=> tests de charge pour le valider/le proposer

**Comment by renaud23** [comment]
Cela ne risque-t-il pas de poser des problèmes de performance côté stockage ?

**Comment by AnneHuSKa** [comment]
API StromaeDSFR ok
