### ISSUE TITLE
Layout for multiple choice questions with list as response

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Stromae#294]
🇬🇧 When designing in Pogues a multiple choice question, we can have as a response domain a code list. Currently, the layout is (1)

But in several cases, we want the code list inline, as in (2). And if the list is too long to fit on one line, ideally we would like something like (3).

🇫🇷 Pour les questions à choix multiples, on peut choisi dans Pogues une réponse sous la forme d'une liste pour chaque item. Aujourd'hui, la présentation est (1).

Mais dans la plupart des cas, le besoin est une présentation en ligne, comme dans (2). Et dans le cas où la liste sort du cadre, on souhaiterait un alignement comme en (3).

(1)

![image](https://github.com/InseeFr/Stromae/assets/1663283/551a5023-cf03-45fa-b9f8-8b81cbceab5b)

(2)

![image](https://github.com/InseeFr/Stromae/assets/1663283/f33bb8e4-6590-45c8-a784-4fd992ab81d6)

(3)

![image](https://github.com/InseeFr/Stromae/assets/1663283/5ad43dba-77b8-4e84-841f-ddbbba04e7d9)

**Comment by AnneHuSKa** [comment]
What about this issue with StromaeDSFR ? Do we need to create a specific component ?

**Comment by ddecrulle** [comment]
It's pretty simple for the DSFR cf https://components.react-dsfr.codegouv.studio/?path=/docs/components-checkbox--default#horizontal

I just need that lunatic send to me a props to indicate horizontal display i needed. 

What it the business rules ?

**Comment by nsenave** [comment]
The component shown in the first screenshot is described as a multiple choice question with a code list for modalities in Pogues, but it is actually a `"Table"` in the Lunatic questionnaire.

**Comment by AnneHuSKa** [comment]
Eno will send a prop.

**Comment by AnneHuSKa** [comment]
to transfer in https://github.com/InseeFr/stromae-dsfr
