### ISSUE TITLE
StromaeV2/V3 : rename confusing props : `readOnly` -> `review`

### ISSUE THREAD

**Issue by laurentC35** [InseeFr/Stromae#404]
Link with new component props in Lunatic : 

- https://github.com/InseeFr/Lunatic/issues/692
- https://github.com/InseeFr/Lunatic/issues/659

⚠️Impact in collect plateform (redirection link to review mode in "Moog" legacy)

**Comment by AnneHuSKa** [comment]
@laurentC35 : on peut clore non ?
