### ISSUE TITLE
Stromae V2 - Random return to the start of a questionnaire, Keycloak client bug

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Stromae#446]
Bug seen on the ESR survey, integrated on the beta platform, with versions __Stromae : 2.4.10 | Lunatic : 2.4.9__.

__Behaviour__

When on a particular sequence, on a random question, the questionnaire is automatically (ie without any user action) positioned at the beginning.

__How to reproduce__

In the ESR questionnaire, starting at the "État de santé général" sequence, answer to the questions, at some place you will experience the bug.

⚠️ We might want a _High priority_ tag in Stromae as we have on others Bowie repos.

**Comment by romaintailhurat** [comment]
From @BulotF : there might be a problem with the questionnaire JSON file (after the specific processing script). 

Issue in stand-by.

**Comment by romaintailhurat** [comment]
Problem identified and linked to the Keycloak client lib, @laurentC35 is working on it.

**Comment by romaintailhurat** [comment]
Still need to be fixed as long as we have Stromae V2 (Familles survey in January).

Targeting november for a fix.

**Comment by AnneHuSKa** [comment]
@romaintailhurat : a new label, a new tag

**Comment by QRuhier** [comment]
closed with #469
